//! `augmentagent code-mode dry-run <messageId>` — end-to-end exerciser for
//! the Code-Mode pipeline.
//!
//! The full Code-Mode draft path (LLM-generated TypeScript → sandboxed Deno
//! run → Rust dispatcher → `Store::log_action_code_mode`) ships in stages:
//! I4 (this PR) wires the Rust dispatcher + sidecar glue, I5 lands the
//! `Reasoner::call_code_mode` prompt that produces the program, and I6
//! flips email to code-mode by default.
//!
//! This subcommand exists so I6's acceptance test (and humans wanting to
//! poke the pipeline) can drive the Rust half against a real Deno sandbox
//! *without* the polling daemon, the LLM, or a real Composio/calendar
//! backing store. It:
//!
//! 1. Looks the message up in the local sqlite (so we use the same shape
//!    the daemon sees).
//! 2. Runs a fixture code-mode program against the v1 manifest + a
//!    [`StubDispatcher`](augmentagent_channel_core::code_mode::StubDispatcher)
//!    that returns canned values for every tool.
//! 3. Persists an `actions` row with `mode='code'`, the program source,
//!    and the serialized tool-call trace via
//!    [`Store::log_action_code_mode`].
//!
//! That last step is the I6 acceptance hook: callers can assert
//! `mode='code'` on the new row to verify the wiring without needing the
//! full LLM in the loop.

use std::sync::Arc;

use anyhow::{anyhow, Context, Result};
use augmentagent_channel_core::code_mode::{
    manifest_v1, run_program, StubDispatcher,
};
use augmentagent_store::{rusqlite, ActionStatus, Store};
use clap::Subcommand;
use serde_json::json;
use tracing::info;

/// `augmentagent code-mode <op>` subcommands.
#[derive(Subcommand, Debug)]
pub enum CodeModeOp {
    /// Run the code-mode draft pipeline against a fixture message end-to-end.
    ///
    /// Loads the email by id, runs a fixture Code-Mode program through the
    /// real Deno sandbox using a stub dispatcher, and writes an
    /// `actions` row with `mode='code'` so #52's acceptance test has
    /// something to assert against.
    DryRun {
        /// The `messageId` of an existing row in the `emails` table.
        #[arg(value_name = "MESSAGE_ID")]
        message_id: String,
    },
}

/// Entry point dispatched from `main.rs`'s `Cmd::CodeMode` arm.
pub async fn run(store: Arc<Store>, op: CodeModeOp) -> Result<()> {
    match op {
        CodeModeOp::DryRun { message_id } => dry_run(store, &message_id).await,
    }
}

async fn dry_run(store: Arc<Store>, message_id: &str) -> Result<()> {
    // 1) Load the message — we only need the fields the daemon would feed
    //    the model. Use `with_conn` rather than adding a one-off store
    //    helper since this is a debug subcommand.
    let loaded: Option<(Option<String>, String, String, Option<String>)> = store
        .with_conn(|c| {
            let mut stmt = c.prepare(
                "SELECT threadId, fromEmail, subject, body \
                 FROM emails WHERE messageId = ?1",
            )?;
            let mut rows = stmt.query(rusqlite::params![message_id])?;
            if let Some(row) = rows.next()? {
                let thread_id: Option<String> = row.get(0)?;
                let from_email: String = row.get(1)?;
                let subject: String = row.get(2)?;
                let body: Option<String> = row.get(3)?;
                Ok(Some((thread_id, from_email, subject, body)))
            } else {
                Ok(None)
            }
        })?;
    let (thread_id, from_email, subject, body) = loaded.ok_or_else(|| {
        anyhow!(
            "no email with messageId={message_id} in this database — \
             seed an `emails` row first (e.g. `augmentagent poll-once --dry-run true`)"
        )
    })?;

    info!(
        message_id = %message_id,
        from = %from_email,
        subject = %subject,
        "code-mode dry-run: loaded fixture message"
    );

    // 2) Fixture code-mode program. Three tool calls so the resulting
    //    trace exercises both data-fetch tools and the terminal `draft`.
    //    Plain JS (no TS annotations) — runner.ts uses indirect eval.
    let program = r#"
        async function main() {
            const hint = await tools.wiki.draftHint({ from: "fixture@example.com" });
            const recent = await tools.db.recentEmailsFrom("fixture@example.com", 7);
            await tools.draft(
                "gmail",
                "hello — generated by code-mode dry-run (" + recent.length + " recent)",
                hint
            );
            return "done";
        }
        main();
    "#;
    let manifest = manifest_v1();
    let dispatcher = StubDispatcher::new(vec![
        ("wiki.draftHint".into(), json!("dry-run hint")),
        ("db.recentEmailsFrom".into(), json!([])),
        ("draft".into(), json!(null)),
    ]);

    eprintln!("--- code-mode program ---\n{program}\n--- /program ---");

    let outcome = run_program(program, &manifest, &dispatcher)
        .await
        .context("code-mode runner failed")?;

    eprintln!("--- code-mode trace ({} entries) ---", outcome.trace.len());
    for (i, rec) in outcome.trace.iter().enumerate() {
        eprintln!(
            "  [{i}] {} args={} {}",
            rec.call,
            serde_json::to_string(&rec.args_summary).unwrap_or_default(),
            match (&rec.result_summary, &rec.error) {
                (Some(r), _) => format!("→ {}", serde_json::to_string(r).unwrap_or_default()),
                (None, Some(e)) => format!("✗ {e}"),
                (None, None) => "(no result)".to_string(),
            }
        );
    }
    eprintln!("--- /trace ---");

    // 3) Persist a `mode='code'` action so the I6 acceptance test can
    //    assert against it. `trace_json` must be a pre-serialized string
    //    — `log_action_code_mode` is the dumb byte-bucket, by design.
    let trace_json = serde_json::to_string(&outcome.trace)
        .context("serialize tool-call trace")?;
    let action_id = store.log_action_code_mode(
        message_id,
        thread_id.as_deref(),
        &from_email,
        &subject,
        body.as_deref(),
        Some("hello — generated by code-mode dry-run"),
        ActionStatus::DryRun,
        program,
        &trace_json,
    )?;

    println!("{}", json!({
        "ok": true,
        "action_id": action_id,
        "mode": "code",
        "trace_len": outcome.trace.len(),
        "final": outcome.final_value,
    }));

    Ok(())
}
