//! Deftform workspace token persisted via `augmentagent-auth` (Linux Secret
//! Service). One slot per connected workspace:
//! `augmentagent/deft/<workspace_id>`. Mirrors `GithubAuth`.
//!
//! Stored payload shape (JSON):
//!
//! ```json
//! {
//!   "workspace_id": "ws_abc123",
//!   "token":        "dft_xxxxxxxxxxxxxxxxxxxx",
//!   "base_url":     "https://deftform.com/api/v1",
//!   "fetched_at_ms": 1776600000000
//! }
//! ```
//!
//! The token is generated by the workspace owner at
//! `https://deftform.com/settings/api`. Per `docs/deft-protocol.md` §2 it is
//! **write-capable** (can inject responses / mutate form settings) — treat as
//! a high-value secret. Token expiry/rotation policy is undocumented and
//! `REQUIRES LIVE VALIDATION`.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use augmentagent_auth::{Auth as KeychainAuth, AuthError as KeychainError};

/// Keychain platform namespace. Combined with the workspace id to form
/// `augmentagent/deft/<workspace_id>`.
pub const KEYCHAIN_PLATFORM: &str = "deft";

/// Documented production base URL (`docs/deft-protocol.md` §2).
pub const DEFAULT_BASE_URL: &str = "https://deftform.com/api/v1";

#[derive(Debug, Error)]
pub enum AuthError {
    #[error("keychain: {0}")]
    Keychain(#[from] KeychainError),
    #[error("json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("invalid auth: {0}")]
    Invalid(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeftAuth {
    /// Deftform workspace id. Doubles as the keychain account slot so the
    /// credential is self-describing.
    pub workspace_id: String,
    /// Workspace access token (Bearer). High-value: write-capable.
    pub token: String,
    /// API base. Defaults to [`DEFAULT_BASE_URL`]; overridable for tests
    /// (mockito) or a future self-hosted Deftform.
    #[serde(default = "default_base_url")]
    pub base_url: String,
    /// Wall-clock ms when the token was last persisted. Surfaced so the user
    /// can spot stale rotations.
    #[serde(default)]
    pub fetched_at_ms: i64,
}

fn default_base_url() -> String {
    DEFAULT_BASE_URL.to_string()
}

impl DeftAuth {
    pub fn validate(&self) -> Result<(), AuthError> {
        if self.workspace_id.is_empty() {
            return Err(AuthError::Invalid("empty workspace_id".into()));
        }
        if self.token.is_empty() {
            return Err(AuthError::Invalid("empty token".into()));
        }
        if self.base_url.is_empty() {
            return Err(AuthError::Invalid("empty base_url".into()));
        }
        Ok(())
    }

    /// Load by workspace id. Caller knows the id — passed on the CLI or
    /// stamped on `Email::account_entity_id` (`deft:<workspace_id>`).
    pub fn load_for_workspace(workspace_id: &str) -> Result<Self, AuthError> {
        let bytes = KeychainAuth::get(KEYCHAIN_PLATFORM, workspace_id)?;
        let parsed: DeftAuth = serde_json::from_slice(&bytes)?;
        parsed.validate()?;
        Ok(parsed)
    }

    pub fn save_to_keychain(&self) -> Result<(), AuthError> {
        self.validate()?;
        let bytes = serde_json::to_vec(self)?;
        KeychainAuth::put(KEYCHAIN_PLATFORM, &self.workspace_id, &bytes)?;
        Ok(())
    }

    pub fn delete_from_keychain(workspace_id: &str) -> Result<(), AuthError> {
        KeychainAuth::delete(KEYCHAIN_PLATFORM, workspace_id)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> DeftAuth {
        DeftAuth {
            workspace_id: "ws_abc123".into(),
            token: "dft_AAAABBBBCCCC".into(),
            base_url: DEFAULT_BASE_URL.into(),
            fetched_at_ms: 1776600000000,
        }
    }

    #[test]
    fn validate_accepts_populated() {
        sample().validate().unwrap();
    }

    #[test]
    fn validate_rejects_empty_workspace() {
        let mut a = sample();
        a.workspace_id.clear();
        assert!(a.validate().is_err());
    }

    #[test]
    fn validate_rejects_empty_token() {
        let mut a = sample();
        a.token.clear();
        assert!(a.validate().is_err());
    }

    #[test]
    fn json_round_trip_and_base_url_default() {
        // base_url omitted ⇒ serde default fills the documented prod URL.
        let json = r#"{"workspace_id":"ws1","token":"dft_x","fetched_at_ms":1}"#;
        let back: DeftAuth = serde_json::from_str(json).unwrap();
        assert_eq!(back.base_url, DEFAULT_BASE_URL);
        back.validate().unwrap();
    }
}
